package:
  name: ferretdb
  version: 1.10.1
  epoch: 0
  description: "A truly Open Source MongoDB alternative"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/FerretDB/FerretDB
      tag: v${{package.version}}
      expected-commit: c8c8ee26d3e5c9ee94180215deec5c6ec4ce8bc7

  - uses: go/build
    with:
      packages: ./cmd/ferretdb
      output: ferretdb
      tags: ferretdb_tigris
      ldflags: -s -w

  - uses: strip

update:
  enabled: true
  github:
    identifier: FerretDB/FerretDB
    strip-prefix: v
