package:
  name: k8sgpt
  version: 0.3.15
  epoch: 0
  description: Giving Kubernetes Superpowers to everyone
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - go
      - build-base
      - git

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/k8sgpt-ai/k8sgpt
      tag: v${{package.version}}
      expected-commit: ac2937c82165d619e8e95b32fc51352ac5fa0e96
      destination: k8sgpt

  - runs: |
      cd k8sgpt
      make build
      install -Dm755 ./bin/k8sgpt "${{targets.destdir}}/usr/bin/k8sgpt"

  - uses: strip

update:
  enabled: true
  github:
    identifier: k8sgpt-ai/k8sgpt
    strip-prefix: v
