package:
  name: libsolv
  version: 0.7.25
  epoch: 0
  description: Library for solving packages and reading repositories
  copyright:
    - license: BSD-3-Clause

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - build-base
      - automake
      - autoconf
      - cmake
      - zlib-dev

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/openSUSE/libsolv
      expected-commit: f1be8bf3dcc7dc14d331adbc97f337fa08e641c9
      tag: ${{package.version}}

  - runs: |
      mkdir build
      cd build
      cmake ..

  - uses: autoconf/make
    with:
      dir: build

  - uses: autoconf/make-install
    with:
      dir: build

  - uses: strip

subpackages:
  - name: libsolv-dev
    pipeline:
      - uses: split/dev
    description: libsolv dev

  - name: libsolv-doc
    pipeline:
      - uses: split/manpages

update:
  enabled: true
  github:
    identifier: openSUSE/libsolv
    use-tag: true
    tag-filter: "0."
