package:
  name: opentf
  version: 0.0_git20230914
  epoch: 0
  copyright:
    - license: MPL-2.0

environment:
  environment:
    CGO_ENABLED: 0

pipeline:
  - uses: fetch
    with:
      # Hack until they cut a release
      uri: https://github.com/opentffoundation/opentf/archive/bb1783c63b8a847fb5c5a04b8a51fe937971fcf6.zip
      expected-sha256: 24a3dc03c0e14dae399da306cc0d67677dce13b293cb9552c61e5dc89e1689a0
      extract: false

  # This is a zip so we have to do some surgery ourselves
  - runs: |
      unzip -q bb1783c63b8a847fb5c5a04b8a51fe937971fcf6.zip
      mv opentf-bb1783c63b8a847fb5c5a04b8a51fe937971fcf6 opentf
      rm bb1783c63b8a847fb5c5a04b8a51fe937971fcf6.zip

  - uses: go/build
    with:
      modroot: opentf
      packages: .
      output: opentf
      ldflags: -s -w

  - uses: strip

subpackages:
  - name: opentf-compat
    description: Compat package for opentf
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/local/bin
          ln -s /usr/bin/opentf "${{targets.subpkgdir}}"/usr/local/bin

  - name: opentf-local-provider-config
    description: Configure opentf to use local providers
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/opentf/provider-mirror
          cat > "${{targets.subpkgdir}}"/opentf/.opentfrc <<EOF
          provider_installation {
            filesystem_mirror {
              path    = "/opentf/provider-mirror"
              include = ["*/*"]
            }
            direct {
              exclude = ["*/*"]
            }
          }
          EOF

update:
  enabled: false
