package:
  name: openrefine
  version: 3.7.5
  epoch: 0
  description: "OpenRefine is a free, open source power tool for working with messy data and improving it"
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - openjdk-20-jre
      - bash
      - wget

environment:
  contents:
    packages:
      - wolfi-base
      - build-base
      - bash
      - openjdk-20-jre

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/OpenRefine/OpenRefine
      tag: ${{package.version}}
      expected-commit: a04fb5fbd0d35d7b727bdca7d34bbca8245427d8

  - name: Set directories
    runs: |
      mkdir -p "${{targets.destdir}}"/usr/bin
      mkdir -p "${{targets.destdir}}"/usr/share/${{package.name}}/
      mkdir -p "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/

  - name: Fix bash path for /usr/share/openrefine/refine
    runs: |
      sed -i '1s|^#!/usr/bin/env bash$|#!/bin/bash|' refine

  - name: Install
    runs: |
      mv benchmark "${{targets.destdir}}"/usr/share/${{package.name}}/
      mv conf "${{targets.destdir}}"/usr/share/${{package.name}}/
      mv extensions "${{targets.destdir}}"/usr/share/${{package.name}}/
      mv graphics "${{targets.destdir}}"/usr/share/${{package.name}}/
      mv IDEs "${{targets.destdir}}"/usr/share/${{package.name}}/
      mv main "${{targets.destdir}}"/usr/share/${{package.name}}/
      mv packaging "${{targets.destdir}}"/usr/share/${{package.name}}/
      mv server "${{targets.destdir}}"/usr/share/${{package.name}}/
      mv LICENSE.txt "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/
      cp pom.xml "${{targets.destdir}}"/usr/share/${{package.name}}/
      cp refine.ini "${{targets.destdir}}"/usr/share/${{package.name}}/
      cp refine "${{targets.destdir}}"/usr/share/${{package.name}}/
      install -m755 openrefine/openrefine "${{targets.destdir}}"/usr/bin/openrefine

  - uses: strip

update:
  enabled: true
  github:
    identifier: OpenRefine/OpenRefine
    use-tag: true
