package:
  name: openrefine
  version: 3.7.5
  epoch: 0
  description: "OpenRefine is a free, open source power tool for working with messy data and improving it"
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - openjdk-11-jre
      - bash
      - wget

environment:
  contents:
    packages:
      - wolfi-base
      - build-base
      - bash
      - openjdk-11-jre
      - openjdk-11
      - maven
      - nodejs-20

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/OpenRefine/OpenRefine/releases/download/${{package.version}}/${{package.name}}-linux-${{package.version}}.tar.gz
      expected-sha256: f4dbb7d7592e6fa2466fd37c2de0e74616b62c908a5d76dd3f5feecfb3d2ff4c

  - name: Build
    runs: |
      #fix script bash path
      sed -i '1s|^#!/usr/bin/env bash$|#!/bin/bash|' refine

      mkdir -p "${{targets.destdir}}"/usr/bin
      mkdir -p "${{targets.destdir}}"/usr/share/${{package.name}}/
      mkdir -p "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/

      mv licenses "${{targets.destdir}}"/usr/share/${{package.name}}/
      mv server "${{targets.destdir}}"/usr/share/${{package.name}}/
      mv webapp "${{targets.destdir}}"/usr/share/${{package.name}}/

      install -m755 refine "${{targets.destdir}}"/usr/share/${{package.name}}/
      install -m 755 refine.ini "${{targets.destdir}}"/usr/share/${{package.name}}/

      install -m755 LICENSE.txt "${{targets.destdir}}"/usr/share/licenses/${{package.name}}/

      install -m755 openrefine.sh "${{targets.destdir}}"/usr/bin/openrefine

  - uses: strip

update:
  enabled: true
  github:
    identifier: OpenRefine/OpenRefine
