package:
  name: timestamp-authority-server
  version: 1.1.2
  epoch: 0
  description: Sigstore Timestamp Authority Server
  target-architecture:
    - all
  copyright:
    - license: Apache-2.0
      paths:
        - "*"

environment:
  contents:
    packages:
      - ca-certificates-bundle
      - busybox
      - git
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sigstore/timestamp-authority
      tag: v${{package.version}}
      expected-commit: 0fe7ba862a2edd29dabbaaf50ea3b339d9f08ff4

  - runs: |
      # ensure clean git tree
      rm .gitconfig
      export GOCACHE=$(mktemp -d)/.cache
      export GOMODCACHE=$(mktemp -d)/mod

      make timestamp-server

      mkdir -p ${{targets.destdir}}/usr/bin
      mv ./bin/timestamp-server ${{targets.destdir}}/usr/bin/

update:
  enabled: true
  github:
    identifier: sigstore/timestamp-authority
    strip-prefix: v
